name: stblis
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - anyio=4.6.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - async-lru=2.0.4
  - attrs=24.2.0
  - babel=2.11.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.3
  - blas=1.0
  - bleach=6.2.0
  - blosc=1.21.6
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.34.3
  - c-blosc2=2.15.1
  - ca-certificates=2024.9.24
  - certifi=2024.8.30
  - cffi=1.17.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - h11=0.14.0
  - hdf5=1.14.3
  - httpcore=1.0.2
  - httpx=0.27.0
  - importlib-metadata=8.5.0
  - importlib_metadata=8.5.0
  - ipykernel=6.29.5
  - jinja2=3.1.4
  - json5=0.9.25
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.7.1
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.0
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.1
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.3.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.27.3
  - krb5=1.21.3
  - ld_impl_linux-64=2.40
  - libaec=1.1.3
  - libcurl=8.10.1
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran-ng=8.2.0
  - libgfortran5=14.2.0
  - libgomp=14.2.0
  - libnghttp2=1.64.0
  - libnsl=2.0.1
  - libopenblas=0.3.21
  - libsodium=1.0.18
  - libsqlite=3.47.0
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - lzo=2.10
  - mistune=2.0.4
  - nbclient=0.8.0
  - nbconvert=7.16.4
  - nbformat=5.10.4
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - notebook-shim=0.2.3
  - numexpr=2.10.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openssl=3.4.0
  - overrides=7.4.0
  - pandocfilters=1.5.0
  - pickleshare=0.7.5
  - pip=24.2
  - prometheus_client=0.21.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py-cpuinfo=9.0.0
  - pycparser=2.21
  - pysocks=1.7.1
  - pytables=3.9.2
  - python=3.9.18
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.20.0
  - python-json-logger=2.0.7
  - python_abi=3.9
  - pyyaml=6.0.2
  - readline=8.2
  - referencing=0.30.2
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.10.6
  - send2trash=1.8.2
  - setuptools=75.1.0
  - six=1.16.0
  - snappy=1.2.1
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.31.1
  - stack_data=0.2.0
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.13
  - tomli=2.0.1
  - traitlets=5.14.3
  - typing_extensions=4.11.0
  - urllib3=2.2.3
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.44.0
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.3.1
  - zlib-ng=2.2.2
  - zstd=1.5.6
  - pip:
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.11.7
      - aiosignal==1.3.1
      - antlr4-python3-runtime==4.9.3
      - appdirs==1.4.4
      - asttokens==2.4.1
      - async-timeout==5.0.1
      - blis==0.1.0
      - charset-normalizer==3.4.0
      - click==8.1.7
      - cmake==3.31.1
      - comm==0.2.2
      - contourpy==1.3.0
      - cycler==0.12.1
      - debugpy==1.8.9
      - dill==0.3.9
      - docker-pycreds==0.4.0
      - exceptiongroup==1.2.2
      - executing==2.1.0
      - filelock==3.16.1
      - fonttools==4.55.0
      - frozenlist==1.5.0
      - fsspec==2024.10.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - idna==3.10
      - importlib-resources==6.4.5
      - ipython==8.18.1
      - jedi==0.19.2
      - joblib==1.4.2
      - jupyter-client==8.6.3
      - kiwisolver==1.4.7
      - lightning-utilities==0.11.9
      - lit==18.1.8
      - markupsafe==3.0.2
      - matplotlib==3.9.2
      - matplotlib-inline==0.1.7
      - mpmath==1.3.0
      - multidict==6.1.0
      - multiprocess==0.70.17
      - networkx==3.2.1
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - omegaconf==2.3.0
      - packaging==24.2
      - pandas==2.2.3
      - parso==0.8.4
      - pathos==0.3.3
      - pathtools==0.1.2
      - pexpect==4.9.0
      - pillow==11.0.0
      - platformdirs==4.3.6
      - pox==0.3.5
      - ppft==1.7.6.9
      - prompt-toolkit==3.0.48
      - propcache==0.2.0
      - protobuf==4.25.5
      - psutil==6.1.0
      - pure-eval==0.2.3
      - pygments==2.18.0
      - pyparsing==3.2.0
      - pytorch-lightning==2.3.3
      - pytz==2024.2
      - pywavelets==1.6.0
      - pyzmq==26.2.0
      - scikit-learn==1.5.2
      - scipy==1.13.1
      - seaborn==0.13.2
      - sentry-sdk==2.19.0
      - setproctitle==1.3.4
      - smmap==5.0.1
      - stack-data==0.6.3
      - sympy==1.13.1
      - threadpoolctl==3.5.0
      - torch==2.0.1
      - torch-geometric==2.6.1
      - torchmetrics==1.6.0
      - torchvision==0.15.2
      - tornado==6.4.2
      - tqdm==4.67.1
      - triton==2.0.0
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - wandb==0.15.12
      - wcwidth==0.2.13
      - yarl==1.18.0